Mod 4, tasks 1-3; Mod 5, tasks 1-3
js-tasks-ru/jsbasic-20220418-2_vovandrelo pull request #5
Opened 2022-05-12 13:37 UTC by vovandrelo

2022-05-12 13:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-13 14:28 UTC, SinimaWath requested changes

2022-05-13 14:28 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  const widthSlide = carousel.offsetWidth;
Попробуй взять carouselInner.offsetWidth

2022-05-15 15:55 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-15 15:59 UTC, vovandrelo commented on 5-module/3-task/index.js
> +  const widthSlide = carousel.offsetWidth;
Да, при такое реализации всё работает, исправил) Новый коммит, вроде, прикрепил

2022-05-16 11:11 UTC, SinimaWath approved these changes

2022-05-16 11:12 UTC, merged